// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8uP-YR1vyYOux6DN2Pt-CwqrfoE9cus',
    appId: '1:703315580403:web:ed8cf315966bd48f6b2e86',
    messagingSenderId: '703315580403',
    projectId: 'meroom-e0917',
    authDomain: 'meroom-e0917.firebaseapp.com',
    storageBucket: 'meroom-e0917.firebasestorage.app',
    measurementId: 'G-YK7T21DF0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIrw9_bpEbozsj_T-9I0Q5f5cb3dJj-Cg',
    appId: '1:703315580403:android:ddd9bca7d747e2446b2e86',
    messagingSenderId: '703315580403',
    projectId: 'meroom-e0917',
    storageBucket: 'meroom-e0917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPE-VM0fALObAGvLvZ0Z3L13M3hGHwUbU',
    appId: '1:703315580403:ios:913f520b905729536b2e86',
    messagingSenderId: '703315580403',
    projectId: 'meroom-e0917',
    storageBucket: 'meroom-e0917.firebasestorage.app',
    iosBundleId: 'com.example.mirumList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPE-VM0fALObAGvLvZ0Z3L13M3hGHwUbU',
    appId: '1:703315580403:ios:913f520b905729536b2e86',
    messagingSenderId: '703315580403',
    projectId: 'meroom-e0917',
    storageBucket: 'meroom-e0917.firebasestorage.app',
    iosBundleId: 'com.example.mirumList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF8uP-YR1vyYOux6DN2Pt-CwqrfoE9cus',
    appId: '1:703315580403:web:77272eb666542a1f6b2e86',
    messagingSenderId: '703315580403',
    projectId: 'meroom-e0917',
    authDomain: 'meroom-e0917.firebaseapp.com',
    storageBucket: 'meroom-e0917.firebasestorage.app',
    measurementId: 'G-8F8RQ7V05E',
  );

}